version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - wget -q https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
      - tar xzf spark-3.1.2-bin-hadoop3.2.tgz
      - export SPARK_HOME=$(pwd)/spark-3.1.2-bin-hadoop3.2
      - export PATH=$SPARK_HOME/bin:$PATH
      - apt-get update
      - apt-get install -y openjdk-8-jdk-headless
      - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

  build:
    commands:
      - echo Running Glue job scripts...
      - export SPARK_HOME=$(pwd)/spark-3.1.2-bin-hadoop3.2
      - export PATH=$SPARK_HOME/bin:$PATH
      - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - python Glue/LoadOnlineRetailToRDS.py

artifacts:
  files:
    - '**/*'
