version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      java: corretto8
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - echo Running Glue job scripts...
      - export JAVA_HOME=/usr/lib/jvm/java-1.8.0
      - python Glue/LoadOnlineRetailToRDS.py

artifacts:
  files:
    - '**/*'
