version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Starting Glue job execution..."
      - aws glue start-job-run --job-name LoadOnlineRetailToRDS --region us-east-1
      - echo "Glue job execution initiated."

artifacts:
  files:
    - '**/*'
