version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-building steps...
      - export PYSPARK_PYTHON=python3
  build:
    commands:
      - echo Running Glue job scripts...
      - python onlineretailprocessing.py
      - python loadtoRDS.py
artifacts:
  files:
    - '**/*'
  discard-paths: yes
